import pandas as pd

succession_data = {
    'Starting_Community': [
       'MG6 (Lolio-Cynosuretum grassland)',
        'MG6 (Lolio-Cynosuretum grassland)',
        'MG6 (Lolio-Cynosuretum grassland)',
        'MG6 (Lolio-Cynosuretum grassland)',
        'MG6 (Lolio-Cynosuretum grassland)',
        'MG9 (Holcus lanatus-Deschampsia cespitosa grassland)',
        'MG9 (Holcus lanatus-Deschampsia cespitosa grassland)',
        'MG9 (Holcus lanatus-Deschampsia cespitosa grassland)',
        'MG9 (Holcus lanatus-Deschampsia cespitosa grassland)',
        'U4 (Festuca ovina-Agrostis capillaris-Galium saxatile grassland)',
        'U4 (Festuca ovina-Agrostis capillaris-Galium saxatile grassland)',
        'U4 (Festuca ovina-Agrostis capillaris-Galium saxatile grassland)',
        'U5 (Nardus stricta-Galium saxatile grassland)',
        'U5 (Nardus stricta-Galium saxatile grassland)',
        'U5 (Nardus stricta-Galium saxatile grassland)',
    ],
    'Succession_Driver': [
       'Invasion of Juncus',
       'Overgrazing & Poaching',
        'Reduced Grazing, Wetter Conditions',
       'Increased soil calcium, Reduced Drainage',
        'Increased Flooding',
        'Invasion of Juncus, reduced competition',
        'Reduced grazing, increased moisture',
       'Improved drainage',
       'Heavy disturbance, reduced competition',
        'Reduced grazing',
        'Drainage deteriorates, preferential grazing',
        'Base-poverty amelioration, preferential grazing',
        'Heavy grazing and continued moisture',
        'Improved drainage, reduced grazing',
        'Invasion of shrubs and trees, ungrazed',
    ],
    'Succession_Pathway': [
        'MG10 (Holcus lanatus-Juncus effusus rush-pasture)',
       'MG10 (Holcus lanatus-Juncus effusus rush-pasture)',
       'MG10 (Holcus lanatus-Juncus effusus rush-pasture)',
       'MG10 (Holcus lanatus-Juncus effusus rush-pasture) (J. inflexus sub-community)',
        'MG10 (Holcus lanatus-Juncus effusus rush-pasture) (Iris pseudacorus sub-community)',
        'MG10 (Holcus lanatus-Juncus effusus rush-pasture)',
       'MG10 (Holcus lanatus-Juncus effusus rush-pasture)',
       'MG6 (Lolio-Cynosuretum grassland) or MG6 (Lolium-Alopecurus-Festuca flood-pasture)',
        'MG10 (Holcus lanatus-Juncus effusus rush-pasture)',
       'MG10 (Holcus lanatus-Juncus effusus rush-pasture) (Holcus lanatus-Trifolium repens sub-community)',
       'MG10 (Holcus lanatus-Juncus effusus rush-pasture) (Poa trivialis sub-community)',
        'MG6 (Lolio-Cynosuretum grassland)',
        'MG10 (Holcus lanatus-Juncus effusus rush-pasture)',
       'U4 (Festuca ovina-Agrostis capillaris-Galium saxatile grassland) (Holcus lanatus-Trifolium repens sub-community)',
         'Woodland',
    ],
        'Relevant_Sub-Community': [
        'Typical sub-community',
       'Typical sub-community',
       'Typical sub-community',
        'Juncus inflexus sub-community',
        'Iris pseudacorus sub-community',
       'Poa trivialis sub-community',
       'Poa trivialis sub-community',
        None,
        'Typical sub-community',
        'Holcus lanatus-Trifolium repens sub-community',
       'Poa trivialis sub-community',
       None,
        'Typical sub-community',
        'Holcus lanatus-Trifolium repens sub-community',
        None,
    ]

}
succession_df = pd.DataFrame(succession_data)
print(succession_df)